"""Generate a first structural, semi-synthetic counterfactual benchmark.

The input context and observed timing come from the real dataset.  Potential
outcomes are generated by explicit equations, so Y(0), Y(1), and the true
individual treatment effect are available for evaluation.  This is a benchmark
generator, not a claim that the synthetic outcomes are clinical ground truth.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Iterable


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, object]]) -> None:
    rows = list(rows)
    if not rows:
        raise ValueError("Cannot write an empty counterfactual table")
    path.parent.mkdir(parents=True, exist_ok=True)
    columns = list(rows[0])
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def parse_time(value: str) -> datetime:
    return datetime.fromisoformat(value)


def stable_uniform(*parts: str) -> float:
    digest = hashlib.sha256("|".join(parts).encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") / 2**64


def nearest_iot_rows(
    readings: list[dict[str, str]], case_id: str, timestamp: datetime
) -> dict[str, str]:
    candidates = [
        row
        for row in readings
        if row["case_id"] == case_id
        and row["station"] == "HYGIENE_STATION"
        and parse_time(row["timestamp"]) <= timestamp
    ]
    if not candidates:
        return {}
    return max(candidates, key=lambda row: parse_time(row["timestamp"]))


def safe_float(row: dict[str, str], key: str, default: float = 0.0) -> float:
    try:
        return float(row.get(key, default))
    except (TypeError, ValueError):
        return default


def build_opportunities(
    events: list[dict[str, str]],
    actions: list[dict[str, str]],
    readings: list[dict[str, str]],
    seed: int,
) -> list[dict[str, object]]:
    # Assignment uses stable hashes so reruns remain reproducible.
    events_by_case: dict[str, list[dict[str, str]]] = defaultdict(list)
    for event in events:
        events_by_case[event["case_id"]].append(event)

    durations = [
        float(row["duration_seconds"])
        for row in actions
        if float(row["duration_seconds"]) > 0
    ]
    median_duration = sorted(durations)[len(durations) // 2]
    duration_by_type: dict[str, list[float]] = defaultdict(list)
    for row in actions:
        duration_by_type[row["trace_type"]].append(float(row["duration_seconds"]))

    rows: list[dict[str, object]] = []
    for action_index, action in enumerate(actions):
        start = parse_time(action["start_time"])
        case_events = sorted(
            events_by_case[action["case_id"]],
            key=lambda row: parse_time(row["timestamp"]),
        )
        previous = [
            event
            for event in case_events
            if parse_time(event["timestamp"]) < start
            and not (
                event["activity"] == "Hand hygiene"
                and event["lifecycle_transition"] == "start"
            )
        ]
        previous_event = previous[-1] if previous else None
        previous_activity = previous_event["activity"] if previous_event else "START"
        seconds_since_previous = (
            (start - parse_time(previous_event["timestamp"])).total_seconds()
            if previous_event
            else 0.0
        )
        iot = nearest_iot_rows(readings, action["case_id"], start)

        disturbance = 1 if action["trace_type"] == "disturbance" else 0
        nfc = safe_float(iot, "s22Pa_nfc_status")
        presence = max(0.0, 1.0 - safe_float(iot, "SeG_ir_long_distance") / 150.0)

        # This is an explicit historical-policy proxy, not an estimated causal
        # effect. Disturbance and proximity make hygiene more likely.
        propensity = min(
            0.95,
            max(0.05, 0.55 + 0.15 * disturbance + 0.20 * nfc + 0.10 * presence),
        )
        assignment = int(
            stable_uniform(action["case_id"], str(action_index), str(seed))
            < propensity
        )

        base_risk = 1.0 + 0.8 * disturbance
        if previous_activity in {"Insert needle", "Remove needle"}:
            base_risk += 0.8
        if previous_activity in {"Disinfect injection site", "Apply tourniquet"}:
            base_risk += 0.4
        base_risk += 0.15 * (1.0 - presence)

        # Structural potential outcomes. Treatment reduces risk but costs time
        # and dispenser use. These coefficients are benchmark assumptions.
        y0_risk = base_risk
        risk_reduction = 0.1 + 0.3 * base_risk + 0.15 * disturbance
        y1_risk = max(0.0, base_risk - risk_reduction)
        expected_duration = (
            sum(duration_by_type[action["trace_type"]])
            / len(duration_by_type[action["trace_type"]])
            if duration_by_type[action["trace_type"]]
            else median_duration
        )
        y0_delay = 0.0
        y1_delay = expected_duration
        y0_consumption = 0.0
        y1_consumption = 1.0 + 0.25 * disturbance
        y0_utility = -y0_risk - 0.05 * y0_delay
        y1_utility = -y1_risk - 0.02 * y1_delay - 0.05 * y1_consumption

        rows.append(
            {
                "case_id": action["case_id"],
                "decision_index": action_index,
                "decision_time": action["start_time"],
                "trace_type": action["trace_type"],
                "previous_activity": previous_activity,
                "seconds_since_previous_event": round(seconds_since_previous, 6),
                "disturbance": disturbance,
                "nfc_status": nfc,
                "hygiene_station_presence_proxy": round(presence, 6),
                "load_cell_observed": safe_float(iot, "s23xq_load_cell_weight"),
                "historical_policy_propensity": round(propensity, 6),
                "action_observed": 1,
                "action_factual": assignment,
                "y0_safety_risk": round(y0_risk, 6),
                "y1_safety_risk": round(y1_risk, 6),
                "y0_process_delay_seconds": round(y0_delay, 6),
                "y1_process_delay_seconds": round(y1_delay, 6),
                "y0_resource_units": round(y0_consumption, 6),
                "y1_resource_units": round(y1_consumption, 6),
                "y0_utility": round(y0_utility, 6),
                "y1_utility": round(y1_utility, 6),
                "true_ite_utility": round(y1_utility - y0_utility, 6),
                "factual_utility": round(
                    y1_utility if assignment else y0_utility, 6
                ),
                "counterfactual_source": "structural_potential_outcomes_v1",
            }
        )
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path(__file__).parent / "preprocessed",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parent / "semi_synthetic" / "counterfactual_opportunities.csv",
    )
    parser.add_argument("--seed", type=int, default=20261001)
    args = parser.parse_args()

    events = read_csv(args.input_dir / "observed_events.csv")
    actions = read_csv(args.input_dir / "observed_hand_hygiene_actions.csv")
    readings = read_csv(args.input_dir / "iot_readings.csv")
    rows = build_opportunities(events, actions, readings, args.seed)
    write_csv(args.output, rows)

    treated = Counter(row["action_factual"] for row in rows)
    mean_ite = sum(float(row["true_ite_utility"]) for row in rows) / len(rows)
    report = {
        "source": "observed_context_plus_structural_potential_outcomes",
        "seed": args.seed,
        "opportunity_count": len(rows),
        "factual_action_counts": dict(treated),
        "mean_true_ite_utility": round(mean_ite, 6),
        "potential_outcomes": ["y0_*", "y1_*"],
        "notes": [
            "Y(0) and Y(1) are generated by explicit benchmark equations.",
            "IoT values provide context; they are not treated as causal outcomes.",
            "The load-cell value is retained as an observed feature, not ml_used.",
            "The coefficients are assumptions for method evaluation, not clinical estimates.",
        ],
    }
    report_path = args.output.with_name("generation_report.json")
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
